version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  target-branch: dev
  ignore:
  - dependency-name: rollup
    versions:
    - 2.38.1
    - 2.38.3
    - 2.38.4
    - 2.38.5
    - 2.39.0
    - 2.39.1
    - 2.40.0
    - 2.41.0
    - 2.41.1
    - 2.41.2
    - 2.41.4
    - 2.41.5
    - 2.42.0
    - 2.42.3
    - 2.42.4
    - 2.44.0
    - 2.45.0
    - 2.45.1
  - dependency-name: gulp-changed
    versions:
    - 4.0.2
